version: '3.8'

services:
  nomina_app:
    build: .
    container_name: aplicativo_biometrico
    ports:
      - "8501:8501"
    volumes:
      - .:/app  
    environment:
      - TZ=America/Bogota
    restart: unless-stopped
