version: '3.8'

services:
  nomina_app:
    build: .
    container_name: aplicativo_biometrico
    network_mode: "host"
    volumes:
      - .:/app  
    environment:
      - TZ=America/Bogota
    restart: unless-stopped
