devices:
- name: CASA_GALVEZ
  ip: 192.168.52.6
  port: 4370
  password: 0
  timeout: 90
- name: CIRUGIA
  ip: 192.168.52.8
  port: 4370
  password: 1
  timeout: 10
- name: ZARZAL
  ip: 192.168.101.56
  port: 4370
  password: 890724
  timeout: 20
- name: CESPEDES
  ip: 192.168.10.69
  port: 4370
  password: 0
  timeout: 10
